export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_LOADING = "GET_POSTS_LOADING";

export const GET_MOST_READ_POST = "GET_MOST_READ_POST";
export const GET_MOST_READ_POST_LOADING = "GET_MOST_READ_POST_LOADING";

export const GET_INTERESTING_POSTS = "GET_INTERESTING_POSTS";
export const GET_INTERESTING_POSTS_LOADING = "GET_INTERESTING_POSTS_LOADING";

export const GET_ADVERSITING="GET_ADVERSITING";
export const GET_ADVERSITING_LOADING="GET_ADVERSITING_LOADING";

export const GET_BANNER="GET_BANNER";
export const GET_BANNER_LOADING="GET_BANNER_LOADING"

export const GET_INTERESTING_IMAGE="GET_INTERESTING_IMAGE"
export const GET_INTERESTING_IMAGE_LOADING="GET_INTERESTING_IMAGE_LOADING"

export const GET_CONTACTS="GET_CONTACTS"

export  const GET_MEDIA="GET_MEDIA"

export const GET_CATEGORIES="GET_CATEGORIES"

